# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fix_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zoom_window(object):
    def setupUi(self, zoom_window):
        zoom_window.setObjectName("zoom_window")
        zoom_window.resize(393, 258)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(zoom_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_lbl = QtWidgets.QLabel(zoom_window)
        self.img_lbl.setText("")
        self.img_lbl.setObjectName("img_lbl")
        self.verticalLayout.addWidget(self.img_lbl)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(zoom_window)
        QtCore.QMetaObject.connectSlotsByName(zoom_window)

    def retranslateUi(self, zoom_window):
        _translate = QtCore.QCoreApplication.translate
        zoom_window.setWindowTitle(_translate("zoom_window", "Zoom Window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zoom_window = QtWidgets.QWidget()
    ui = Ui_zoom_window()
    ui.setupUi(zoom_window)
    zoom_window.show()
    sys.exit(app.exec_())
