# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vertical_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vertical_Win(object):
    def setupUi(self, Vertical_Win):
        Vertical_Win.setObjectName("Vertical_Win")
        Vertical_Win.resize(129, 379)
        Vertical_Win.setMaximumSize(QtCore.QSize(129, 379))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Vertical_Win)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lms_btn = QtWidgets.QPushButton(Vertical_Win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lms_btn.sizePolicy().hasHeightForWidth())
        self.lms_btn.setSizePolicy(sizePolicy)
        self.lms_btn.setObjectName("lms_btn")
        self.verticalLayout.addWidget(self.lms_btn)
        self.rms_btn = QtWidgets.QPushButton(Vertical_Win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rms_btn.sizePolicy().hasHeightForWidth())
        self.rms_btn.setSizePolicy(sizePolicy)
        self.rms_btn.setObjectName("rms_btn")
        self.verticalLayout.addWidget(self.rms_btn)
        self.scroll_btn = QtWidgets.QPushButton(Vertical_Win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_btn.sizePolicy().hasHeightForWidth())
        self.scroll_btn.setSizePolicy(sizePolicy)
        self.scroll_btn.setObjectName("scroll_btn")
        self.verticalLayout.addWidget(self.scroll_btn)
        self.show_keyboard_btn = QtWidgets.QPushButton(Vertical_Win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_keyboard_btn.sizePolicy().hasHeightForWidth())
        self.show_keyboard_btn.setSizePolicy(sizePolicy)
        self.show_keyboard_btn.setObjectName("show_keyboard_btn")
        self.verticalLayout.addWidget(self.show_keyboard_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Vertical_Win)
        QtCore.QMetaObject.connectSlotsByName(Vertical_Win)

    def retranslateUi(self, Vertical_Win):
        _translate = QtCore.QCoreApplication.translate
        Vertical_Win.setWindowTitle(_translate("Vertical_Win", "Buttons Window"))
        self.lms_btn.setText(_translate("Vertical_Win", "LMS"))
        self.rms_btn.setText(_translate("Vertical_Win", "RMS"))
        self.scroll_btn.setText(_translate("Vertical_Win", "Scroll Mode"))
        self.show_keyboard_btn.setText(_translate("Vertical_Win", "Show Keyboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Vertical_Win = QtWidgets.QWidget()
    ui = Ui_Vertical_Win()
    ui.setupUi(Vertical_Win)
    Vertical_Win.show()
    sys.exit(app.exec_())
